spring.application.name=book-swap

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/bookStore}

# Server
server.port=${PORT:4000}

# CORS
frontend.url=${FRONTEND_URL:http://localhost:5173}
